202235275 심찬기

In [5]:
import numpy as np
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

docs = [ 'additional income',
'best price',
'big bucks',
'cash bonus',
'earn extra cash',
'spring savings certificate',
'valero gas marketing',
'all domestic employees',
'nominations for oct',
'confirmation from spinner']

labels = np.array([1,1,1,1,1,0,0,0,0,0])


In [15]:
vocab_size=50
encoded_docs = [one_hot(d,vocab_size) for d in docs]
print(encoded_docs)

[[30, 13], [13, 45], [42, 19], [31, 12], [31, 46, 31], [15, 48, 30], [39, 45, 23], [48, 17, 45], [3, 32, 33], [29, 8, 24]]


In [14]:
max_length = 4
padded_docs = pad_sequences(encoded_docs,maxlen=max_length, padding='post')
print(padded_docs)

[[30 13  0  0]
 [13 45  0  0]
 [42 19  0  0]
 [31 12  0  0]
 [31 46 31  0]
 [15 48 30  0]
 [39 45 23  0]
 [48 17 45  0]
 [ 3 32 33  0]
 [29  8 24  0]]


In [16]:
model = Sequential()
model.add(Embedding(vocab_size, 8 , input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
model.fit(padded_docs,labels, epochs=50, verbose=0)

loss,accuracy = model.evaluate(padded_docs,labels,verbose=0)
print('정확도', accuracy)

정확도 1.0


In [18]:
test_doc=['big income']
encoded_docs = [one_hot(d, vocab_size) for d in test_doc]
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')

print(model.predict(padded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
[[0.5576302]]
